### ISSUE TITLE
Insufficient memory to continue

### ISSUE THREAD

**Issue by GameplayGoon** [erfg12/memory.dll#120]
I was told to post here since this seems to be an optimization bug when AOB Scanning. Im getting this error message on some games when searching in specific sections of the games memory. It seems to be when searching outside of a module but I could be wrong, does not happen on all games. The AOB scans work fine in Cheat Engine but not when using the module so I know there correct. Thanks

Code Used:
`aobscan = m.AoBScan("03 00 00 00 ? ? ? ? 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 34 42 00 00 00 00 00 00 20 41 00 00 A0 40 00 00 80 3F", True).Result.FirstOrDefault.ToString("X8")`

Error Message:
```
System.OutOfMemoryException
  HResult=0x8007000E
  Message=Insufficient memory to continue the execution of the program.
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
   at Memory.Mem.CompareScan(MemoryRegionResult item, Byte[] aobPattern, Byte[] mask) in C:\Users\newgm\Documents\git\memory.dll\Memory\memory.cs:line 2035
   at Memory.Mem.<>c__DisplayClass120_1.<AoBScan>b__1(MemoryRegionResult item, ParallelLoopState parallelLoopState, Int64 index) in C:\Users\newgm\Documents\git\memory.dll\Memory\memory.cs:line 2003
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__2(Int32 i, ParallelLoopState state)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()

  This exception was originally thrown at this call stack:
    [External Code]
    Memory.Mem.CompareScan(Memory.MemoryRegionResult, byte[], byte[]) in memory.cs
    Memory.Mem.AoBScan.AnonymousMethod__1(Memory.MemoryRegionResult, System.Threading.Tasks.ParallelLoopState, long) in memory.cs
    [External Code]
```

**Comment by erfg12** [comment]
@hollow87 Further research is needed.
