### ISSUE TITLE
ReadFloat, System.FormatException: 'Input string was not in a correct format'

### ISSUE THREAD

**Issue by kotikgem** [erfg12/memory.dll#122]
![photo_2021-09-28_00-48-08](https://user-images.githubusercontent.com/91488709/134983507-c4dbec1a-7d2e-4b9b-a62a-c4201190a1de.jpg)
System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s, NumberStyles style)
   at Memory.Mem.GetCode(String name, String path, Int32 size)
   at Memory.Mem.ReadFloat(String code, String file, Boolean round)
   at memtest.Program.Main(String[] args) in C:\Users\zKotikGem\Source\Repos\memtest\memtest\Program.cs:line 17

**Comment by erfg12** [comment]
Try removing the spaces please.
