### ISSUE TITLE
Estouro no AoBScan memory.dll C# / Overflow in AoBScan memory.dll C#

### ISSUE THREAD

**Issue by Menordabierre** [erfg12/memory.dll#171]
IEnumerable<long> results = await MemLib.AoBScan(0x0000000001ffffff, 0x000000001fffffff, "FF FF FF FF 00 00 00 00 00 4A");

Já não sei mais o que fazer espero que alguem posso me ajudar. / I don't know what to do anymore, I hope someone can help me.

************** Texto de Exceção **************
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.UIntPtr..ctor(UInt64 value)
   at Memory.Mem.<>c__DisplayClass34_0.<AoBScan>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hack.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\User\Desktop\Hack-C#\Hack\Hack\Form1.cs:line 44
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by iBadassCheats** [comment]
long results = await MemLib.AoBScan(0x000000000fffffff, 0x000000002fffffff, "FF FF FF FF 00 00 00 00 00 4A");

**Comment by erfg12** [comment]
That's a very vague section of memory. I wouldn't recommend scanning for it.
